"""add_user_id_to_search_models

Revision ID: d0e8d780cdb0
Revises: 013
Create Date: 2026-04-29 20:18:49.511288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0e8d780cdb0'
down_revision: Union[str, Sequence[str], None] = '013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_import_jobs_created_at'), table_name='import_jobs')
    op.drop_index(op.f('idx_import_jobs_status'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.add_column('annotations', sa.Column('color', sa.String(length=20), nullable=False))
    op.drop_column('annotations', 'highlight_color')
    op.alter_column('collections', 'icon',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.execute("UPDATE collections SET user_id = (SELECT id FROM users LIMIT 1) WHERE user_id IS NULL")
    op.alter_column('collections', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('collections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('collections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_collections_user_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.drop_column('collections', 'is_system')
    op.alter_column('content', 'enrichment_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.execute("UPDATE content SET user_id = (SELECT id FROM users LIMIT 1) WHERE user_id IS NULL")
    op.alter_column('content', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('content_source_url_user_id_key'), table_name='content')
    op.drop_index(op.f('idx_content_created_is_read'), table_name='content')
    op.drop_index(op.f('idx_content_difficulty'), table_name='content')
    op.drop_index(op.f('idx_content_domain'), table_name='content')
    op.drop_index(op.f('idx_content_enrichment_status'), table_name='content')
    op.drop_index(op.f('idx_content_is_read'), table_name='content')
    op.drop_index(op.f('idx_content_reading_progress'), table_name='content')
    op.drop_index(op.f('idx_content_user_id'), table_name='content')
    op.create_index(op.f('ix_content_domain'), 'content', ['domain'], unique=False)
    op.alter_column('content_collections', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_content_collections_collection_id'), table_name='content_collections')
    op.drop_index(op.f('ix_content_collections_content_id'), table_name='content_collections')
    op.drop_constraint(op.f('uq_content_collection'), 'content_collections', type_='unique')
    op.create_index('idx_cc_collection_id', 'content_collections', ['collection_id'], unique=False)
    op.create_index('idx_cc_content_id', 'content_collections', ['content_id'], unique=False)
    op.drop_column('content_collections', 'id')
    # Add user_id to saved_searches as nullable initially
    op.add_column('saved_searches', sa.Column('user_id', sa.UUID(), nullable=True))
    
    # Add user_id to search_history as nullable initially
    op.add_column('search_history', sa.Column('user_id', sa.UUID(), nullable=True))
    
    # Update existing rows with a default user_id if any rows exist
    # This is a bit hacky but works for development
    op.execute("""
        UPDATE saved_searches SET user_id = (SELECT id FROM users LIMIT 1) WHERE user_id IS NULL;
        UPDATE search_history SET user_id = (SELECT id FROM users LIMIT 1) WHERE user_id IS NULL;
    """)
    
    # Now set them to NOT NULL
    op.alter_column('saved_searches', 'user_id', nullable=False)
    op.alter_column('search_history', 'user_id', nullable=False)
    
    op.alter_column('saved_searches', 'mode',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("'hybrid'::character varying"))
    op.create_index('idx_saved_searches_user_id', 'saved_searches', ['user_id'], unique=False)
    op.create_foreign_key(None, 'saved_searches', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    op.alter_column('search_history', 'mode',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index('idx_search_history_user_id', 'search_history', ['user_id'], unique=False)
    op.create_foreign_key(None, 'search_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'search_history', type_='foreignkey')
    op.drop_index('idx_search_history_user_id', table_name='search_history')
    op.alter_column('search_history', 'mode',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('search_history', 'user_id')
    op.drop_constraint(None, 'saved_searches', type_='foreignkey')
    op.drop_index('idx_saved_searches_user_id', table_name='saved_searches')
    op.alter_column('saved_searches', 'mode',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'hybrid'::character varying"))
    op.drop_column('saved_searches', 'user_id')
    op.add_column('content_collections', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index('idx_cc_content_id', table_name='content_collections')
    op.drop_index('idx_cc_collection_id', table_name='content_collections')
    op.create_unique_constraint(op.f('uq_content_collection'), 'content_collections', ['content_id', 'collection_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_content_collections_content_id'), 'content_collections', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_collections_collection_id'), 'content_collections', ['collection_id'], unique=False)
    op.alter_column('content_collections', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_content_domain'), table_name='content')
    op.create_index(op.f('idx_content_user_id'), 'content', ['user_id'], unique=False)
    op.create_index(op.f('idx_content_reading_progress'), 'content', ['reading_progress'], unique=False)
    op.create_index(op.f('idx_content_is_read'), 'content', ['is_read'], unique=False)
    op.create_index(op.f('idx_content_enrichment_status'), 'content', ['enrichment_status'], unique=False)
    op.create_index(op.f('idx_content_domain'), 'content', ['domain'], unique=False)
    op.create_index(op.f('idx_content_difficulty'), 'content', ['difficulty'], unique=False)
    op.create_index(op.f('idx_content_created_is_read'), 'content', ['created_at', 'is_read'], unique=False)
    op.create_index(op.f('content_source_url_user_id_key'), 'content', ['source_url', 'user_id'], unique=True)
    op.alter_column('content', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('content', 'enrichment_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.add_column('collections', sa.Column('is_system', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=False)
    op.create_index(op.f('idx_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.alter_column('collections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('collections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('collections', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('collections', 'icon',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('annotations', sa.Column('highlight_color', sa.VARCHAR(length=20), server_default=sa.text("'yellow'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('annotations', 'color')
    op.create_table('import_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('total_items', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_items', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('failed_items', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("source_type::text = ANY (ARRAY['pocket'::character varying, 'raindrop'::character varying, 'bookmarks'::character varying]::text[])", name=op.f('ck_source_type')),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])", name=op.f('ck_job_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('import_jobs_pkey'))
    )
    op.create_index(op.f('idx_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    op.create_index(op.f('idx_import_jobs_created_at'), 'import_jobs', ['created_at'], unique=False)
    # ### end Alembic commands ###
